version: '3.8'

services:
  server:
    build: .
    container_name: mywebserver
    ports:
      - "1316:1316"
    command: >
      bash -c "
      rm -rf build/release;
      cmake --preset release &&
      cmake --build build/release &&
      ./build/release/server/src/server
      "
