name: C++ Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Docker Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build and Run in Docker
        timeout-minutes: 15
        run: |
          docker compose up --build -d
          
          echo "Waiting for container to initialize..."
          sleep 10
          
          if [ $(docker inspect -f '{{.State.Running}}' mywebserver) != "true" ]; then
            echo "Container crashed immediately!"
            docker compose logs
            exit 1
          fi
          
          docker compose logs
          
          docker compose down